# Generated by Django 5.0.3 on 2024-04-02 09:46

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import kuaförApp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Firma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firma_kod", models.CharField(max_length=6, unique=True)),
                ("firma_adi", models.CharField(max_length=255)),
                ("firma_adres", models.CharField(max_length=255)),
                ("firma_telefon", models.CharField(max_length=255)),
                (
                    "firma_telefon2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("firma_sehir", models.CharField(max_length=255)),
                ("firma_ilce", models.CharField(max_length=255)),
                ("firma_ünvan", models.CharField(max_length=255)),
                ("firma_dis_ip", models.CharField(max_length=255)),
                ("firma_durum", models.BooleanField(default=True)),
                ("firma_bas_tar", models.DateTimeField()),
                ("firma_bit_tar", models.DateTimeField()),
                (
                    "firma_create_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("firma_create_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FirmaUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("user_frm_kod", models.CharField(max_length=255, null=True)),
                ("user_adi", models.CharField(max_length=255)),
                ("user_soyad", models.CharField(max_length=255)),
                ("user_durum", models.BooleanField(default=True)),
                ("user_kayit_yetki", models.IntegerField(default=0)),
                ("user_sil_yetki", models.IntegerField(default=0)),
                (
                    "user_kayit_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("user_kayit_zaman", models.DateTimeField(auto_now_add=True)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("username", models.CharField(max_length=30)),
                (
                    "groups",
                    models.ManyToManyField(related_name="firma_users", to="auth.group"),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        related_name="firma_users", to="auth.permission"
                    ),
                ),
                (
                    "user_firma",
                    models.ManyToManyField(
                        related_name="firma_users", to="kuaförApp.firma"
                    ),
                ),
            ],
            options={
                "permissions": (("kullanicilari_listele", "kullanicilari_listele"),),
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Kat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kat_frm_kod", models.CharField(max_length=20)),
                ("kat_ad", models.CharField(max_length=20)),
                ("kat_durum", models.BooleanField(default=True)),
                ("kat_kayit_tar", models.DateTimeField(auto_now_add=True)),
                ("kat_kayit_user", models.CharField(max_length=50)),
                (
                    "kat_firma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kuaförApp.firma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kategori_frm_kod", models.CharField(max_length=20)),
                ("kategori_kod", models.CharField(max_length=20)),
                ("kategori_ad", models.CharField(max_length=20)),
                (
                    "kategori_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=kuaförApp.models.kategori_resim_yolu,
                    ),
                ),
                ("kategori_durum", models.BooleanField(default=True)),
                ("kategori_kayit_user", models.CharField(max_length=20)),
                ("kategori_kayit_zaman", models.DateTimeField(auto_now_add=True)),
                (
                    "kategori_frm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kuaförApp.firma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Masa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("masa_frm_kod", models.CharField(max_length=20)),
                ("masa_num", models.CharField(max_length=20)),
                ("masa_durum", models.BooleanField(default=True)),
                ("masa_kayit_tar", models.DateTimeField(auto_now_add=True)),
                ("masa_kayit_user", models.CharField(max_length=50)),
                (
                    "masa_firma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kuaförApp.firma",
                    ),
                ),
                (
                    "masa_kat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kuaförApp.kat"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Siparis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("siparis_frm_kod", models.CharField(max_length=20)),
                ("siparis_tar", models.DateTimeField(auto_now_add=True)),
                ("siparis_sıra_num", models.IntegerField()),
                (
                    "siparis_durum",
                    models.IntegerField(
                        choices=[
                            (0, "Beklemede"),
                            (1, "Hazırlanıyor (Onaylandı)"),
                            (2, "Hazırlandı"),
                            (9, "İptal Edildi"),
                        ],
                        default=0,
                    ),
                ),
                ("siparis_miktar", models.IntegerField()),
                ("siparis_kayıt_zaman", models.DateTimeField(auto_now_add=True)),
                ("siparis_hazir_zaman", models.DateTimeField(blank=True, null=True)),
                ("siparis_masa", models.CharField(max_length=50)),
                (
                    "siparis_frm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kuaförApp.firma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Urun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urun_frm_kod", models.CharField(max_length=20)),
                ("urun_ad", models.CharField(max_length=255)),
                ("urun_durum", models.BooleanField(default=True)),
                (
                    "urun_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=kuaförApp.models.urun_resim_yolu,
                    ),
                ),
                ("urun_fiyat", models.IntegerField()),
                ("urun_kayit_user", models.CharField(max_length=20)),
                ("urun_kayit_zaman", models.DateTimeField(auto_now_add=True)),
                (
                    "urun_frm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kuaförApp.firma",
                    ),
                ),
                (
                    "urun_kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kuaförApp.kategori",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiparisUrun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miktar", models.IntegerField(default=1)),
                (
                    "siparis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kuaförApp.siparis",
                    ),
                ),
                (
                    "urun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kuaförApp.urun"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="siparis",
            name="siparis_ürünler",
            field=models.ManyToManyField(to="kuaförApp.urun"),
        ),
    ]
