# Generated by Django 5.0.3 on 2024-04-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kuaförApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siparis",
            name="siparis_sıra_num",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
