# Generated by Django 5.0.3 on 2024-04-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kuaförApp", "0002_alter_siparis_siparis_sıra_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siparis",
            name="siparis_miktar",
        ),
        migrations.RemoveField(
            model_name="siparis",
            name="siparis_ürünler",
        ),
        migrations.AlterField(
            model_name="siparisurun",
            name="miktar",
            field=models.IntegerField(),
        ),
    ]
