# Generated by Django 5.0.3 on 2024-04-02 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kuaförApp", "0003_remove_siparis_siparis_miktar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siparisurun",
            name="siparis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="siparis_urunleri",
                to="kuaförApp.siparis",
            ),
        ),
    ]
