# Generated by Django 5.0.3 on 2024-04-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kuaförApp", "0004_alter_siparisurun_siparis"),
    ]

    operations = [
        migrations.AddField(
            model_name="siparis",
            name="siparis_fis_num",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
