# Generated by Django 5.0.3 on 2024-04-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kuaförApp", "0005_siparis_siparis_fis_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siparis",
            name="siparis_durum",
            field=models.IntegerField(
                choices=[
                    (0, "Beklemede"),
                    (1, "Onaylandı"),
                    (2, "Hazırlandı"),
                    (9, "İptal Edildi"),
                ],
                default=0,
            ),
        ),
    ]
