# Generated by Django 5.0.3 on 2024-04-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kuaförApp", "0006_alter_siparis_siparis_durum"),
    ]

    operations = [
        migrations.AddField(
            model_name="masa",
            name="masa_qr_code",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
