# Generated by Django 5.0.3 on 2024-04-06 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kuaförApp", "0008_remove_masa_masa_qr_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url_frm_kod", models.CharField(max_length=6)),
                ("url_frm_ip", models.CharField(max_length=25)),
                ("url_durum", models.BooleanField(default=1)),
                (
                    "url_frm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kuaförApp.firma",
                        to_field="firma_kod",
                    ),
                ),
                (
                    "url_masa_kat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kuaförApp.kat"
                    ),
                ),
                (
                    "url_masa_num",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kuaförApp.masa"
                    ),
                ),
            ],
        ),
    ]
