# Generated by Django 5.0.3 on 2024-04-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kuaförApp", "0009_shorturl"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorturl",
            name="url",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shorturl",
            name="url_qr_code",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
