# Generated by Django 5.0.3 on 2024-04-06 15:42

import kuaförApp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kuaförApp", "0011_masa_masa_short_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="url_qr_code",
            field=models.ImageField(upload_to=kuaförApp.models.get_media_path),
        ),
    ]
