# Generated by Django 5.0.3 on 2024-04-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kuaförApp", "0012_alter_shorturl_url_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firmauser",
            name="username",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
