# Generated by Django 5.0.3 on 2024-04-11 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kuaförApp", "0014_alter_firmauser_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="firmauser",
            options={
                "permissions": (
                    ("kullanicilari_listele", "kullanicilari_listele"),
                    ("kullanici_kayit", "Kullanıcı Kayıt"),
                )
            },
        ),
    ]
