# Generated by Django 5.0.3 on 2024-04-11 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kuaförApp", "0015_alter_firmauser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="firmauser",
            options={
                "permissions": (
                    ("kullanicilari_listele", "Kullanıcıları Listele"),
                    ("kullanici_kayit", "Kullanıcı Kayıt"),
                    ("ürünleri_gör", "Ürünleri Gör"),
                )
            },
        ),
        migrations.RemoveField(
            model_name="firmauser",
            name="user_kayit_yetki",
        ),
        migrations.RemoveField(
            model_name="firmauser",
            name="user_sil_yetki",
        ),
    ]
