# Generated by Django 5.0.4 on 2024-04-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0021_alter_firmauser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmauser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
