# Generated by Django 5.0.4 on 2024-04-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0022_alter_firmauser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmauser',
            name='user_adres',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firmauser',
            name='user_cinsiyet',
            field=models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kadın'), ('B', 'Diğer')], default='Belirtilmedi', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='firmauser',
            name='user_dogum_tarihi',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='firmauser',
            name='user_telefon',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
