# Generated by Django 5.0.4 on 2024-04-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0023_firmauser_user_adres_firmauser_user_cinsiyet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmauser',
            name='user_user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
