# Generated by Django 5.0.4 on 2024-04-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0024_firmauser_user_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmauser',
            name='user_cinsiyet',
            field=models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kadın'), ('B', 'Belirtilmedi')], default='Belirtilmedi', max_length=20, null=True),
        ),
    ]
