# Generated by Django 5.0.4 on 2024-04-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0027_alter_firmauser_user_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmauser',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
