# Generated by Django 5.0.4 on 2024-04-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0028_alter_firmauser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmauser',
            name='user_dogum_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
