# Generated by Django 5.0.4 on 2024-04-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0029_alter_firmauser_user_dogum_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmauser',
            name='user_adi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='firmauser',
            name='user_soyad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
