# Generated by Django 5.0.4 on 2024-04-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0030_alter_firmauser_user_adi_alter_firmauser_user_soyad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmauser',
            old_name='user_user_email',
            new_name='user_email',
        ),
    ]
