# Generated by Django 5.0.4 on 2024-04-20 23:08

import kuaförApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0031_rename_user_user_email_firmauser_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmauser',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to=kuaförApp.models.user_image_path),
        ),
    ]
