# Generated by Django 5.0.4 on 2024-04-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0032_firmauser_user_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmauser',
            options={'permissions': (('firma_ekle', 'Firma Ekle'), ('firmalari_listele', 'Firmaları Listele'), ('tanimlari_listele', 'Tanımları Listele'), ('kullanicilari_listele', 'Kullanıcıları Listele'), ('ürünleri_listele', 'Ürünleri Listele'), ('konumlari_listele', 'Konumları Listele'), ('masalari_listele', 'Masaları Listele'), ('kategorileri_listele', 'Kategorileri Listele'), ('kullanici_ekle', 'Kullanıcı Ekle'), ('ürün_ekle', 'Ürün Ekle'), ('konum_ekle', 'Konum Ekle'), ('masa_ekle', 'Masa Ekle'), ('kategori_ekle', 'Kategori Ekle'), ('kullanici_kayit', 'Kullanıcı Kayıt'), ('ürünleri_gör', 'Ürünleri Gör'))},
        ),
    ]
