# Generated by Django 5.0.4 on 2024-04-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kuaförApp', '0040_alter_firmauser_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmauser',
            options={'permissions': (('firma_ekle', 'Firma Ekle'), ('firmalari_listele', 'Firmaları Listele'), ('firma_düzenle', 'Firma Düzenle'), ('tanimlari_listele', 'Tanımları Listele'), ('kullanicilari_listele', 'Kullanıcıları Listele'), ('ürünleri_listele', 'Ürünleri Listele'), ('konumlari_listele', 'Konumları Listele'), ('masalari_listele', 'Masaları Listele'), ('kategorileri_listele', 'Kategorileri Listele'), ('kullanici_ekle', 'Kullanıcı Ekle'), ('ürün_ekle', 'Ürün Ekle'), ('konum_ekle', 'Konum Ekle'), ('masa_ekle', 'Masa Ekle'), ('kategori_ekle', 'Kategori Ekle'), ('kullanici_kayit', 'Kullanıcı Kayıt'), ('ürünleri_gör', 'Ürünleri Gör'))},
        ),
        migrations.AlterField(
            model_name='firmauser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='firma_users', to='auth.permission'),
        ),
    ]
