# Generated by Django 5.0.4 on 2024-04-24 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0051_alter_firmauser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmauser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.CreateModel(
            name='Yetki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_ekle', models.BooleanField(default=False)),
                ('firmalari_listele', models.BooleanField(default=False)),
                ('firma_duzenle', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yetkiler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
