# Generated by Django 5.0.4 on 2024-04-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kuaförApp', '0052_alter_firmauser_options_yetki'),
    ]

    operations = [
        migrations.AddField(
            model_name='yetki',
            name='kategori_ekle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yetki',
            name='kategorileri_listele',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yetki',
            name='konum_ekle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yetki',
            name='kullanici_ekle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yetki',
            name='kullanici_kayit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yetki',
            name='masa_ekle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yetki',
            name='masalari_listele',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yetki',
            name='tanimlari_listele',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yetki',
            name='ürün_ekle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yetki',
            name='ürünleri_gör',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yetki',
            name='ürünleri_listele',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='firmauser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
