# Generated by Django 5.0.4 on 2024-04-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0055_yetki_kullanicilari_listele'),
    ]

    operations = [
        migrations.AddField(
            model_name='yetki',
            name='firma_sil',
            field=models.BooleanField(default=False),
        ),
    ]
