# Generated by Django 5.0.4 on 2024-04-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0057_yetki_urun_guncelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmauser',
            name='user_tag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
