# Generated by Django 5.0.4 on 2024-04-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0058_firmauser_user_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='yetki',
            name='kullanici_guncelle',
            field=models.BooleanField(default=False),
        ),
    ]
