# Generated by Django 5.0.4 on 2024-04-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0059_yetki_kullanici_guncelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='yetki',
            name='kullanici_yetkilendir',
            field=models.BooleanField(default=False),
        ),
    ]
