# Generated by Django 5.0.4 on 2024-04-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0060_yetki_kullanici_yetkilendir'),
    ]

    operations = [
        migrations.AddField(
            model_name='yetki',
            name='guncelleme_talepleri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yetki',
            name='hata_talepleri',
            field=models.BooleanField(default=False),
        ),
    ]
