# Generated by Django 5.0.4 on 2024-04-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0061_yetki_guncelleme_talepleri_yetki_hata_talepleri'),
    ]

    operations = [
        migrations.AddField(
            model_name='yetki',
            name='masa_duzenle',
            field=models.BooleanField(default=False),
        ),
    ]
