# Generated by Django 5.0.4 on 2024-04-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0062_yetki_masa_duzenle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yetki',
            old_name='masa_duzenle',
            new_name='masa_guncelle',
        ),
    ]
