# Generated by Django 5.0.4 on 2024-05-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0063_rename_masa_duzenle_yetki_masa_guncelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='yetki',
            name='firma_durum_degistir',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='siparis_durum',
            field=models.IntegerField(choices=[(1, 'Onaylandı'), (2, 'Hazırlandı'), (9, 'İptal Edildi')], default=0),
        ),
    ]
