# Generated by Django 5.0.4 on 2024-05-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0064_yetki_firma_durum_degistir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yetki',
            name='deneme_yetki',
            field=models.BooleanField(default=False),
        ),
    ]
