# Generated by Django 5.0.4 on 2024-05-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0065_yetki_deneme_yetki'),
    ]

    operations = [
        migrations.AddField(
            model_name='yetki',
            name='deneme_yetki1',
            field=models.BooleanField(default=False),
        ),
    ]
