# Generated by Django 5.0.4 on 2024-05-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0066_yetki_deneme_yetki1'),
    ]

    operations = [
        migrations.AddField(
            model_name='yetki',
            name='deneme_yetki2',
            field=models.BooleanField(default=False),
        ),
    ]
