# Generated by Django 5.0.4 on 2024-05-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0067_yetki_deneme_yetki2'),
    ]

    operations = [
        migrations.AddField(
            model_name='yetki',
            name='deneme_yetki3',
            field=models.BooleanField(default=False),
        ),
    ]
