# Generated by Django 5.0.4 on 2024-05-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0068_yetki_deneme_yetki3'),
    ]

    operations = [
        migrations.AddField(
            model_name='yetki',
            name='deneme_yetki4',
            field=models.BooleanField(default=False),
        ),
    ]
