# Generated by Django 5.0.4 on 2024-05-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0071_yetki_deneme_yetki6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yetki',
            name='deneme_yetki6',
        ),
    ]
