# Generated by Django 5.0.4 on 2024-05-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0074_yetki_deneme_yetki7'),
    ]

    operations = [
        migrations.AddField(
            model_name='yetki',
            name='deneme_yetki8',
            field=models.BooleanField(default=False),
        ),
    ]
