# Generated by Django 5.0.4 on 2024-05-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0075_yetki_deneme_yetki8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='siparis_durum',
            field=models.IntegerField(choices=[(1, 'Onaylandı'), (2, 'Hazırlandı'), (3, 'Tamamlandı'), (9, 'İptal Edildi')], default=0),
        ),
    ]
