# Generated by Django 5.0.4 on 2024-05-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0076_alter_siparis_siparis_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='siparis_durum',
            field=models.IntegerField(choices=[(1, 'Bekleyen'), (2, 'Hazırlandı'), (3, 'Tamamlandı'), (9, 'İptal Edildi')], default=0),
        ),
    ]
