# Generated by Django 5.0.4 on 2024-05-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0077_alter_siparis_siparis_durum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adresi', models.CharField(max_length=255)),
                ('zaman', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
