# Generated by Django 5.0.4 on 2024-05-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0078_yetki_kullanici_güncelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_company_code', models.CharField(max_length=10)),
                ('req_user', models.CharField(max_length=255)),
                ('company_code', models.BooleanField(default=False)),
                ('company_name', models.BooleanField(default=False)),
                ('company_address', models.BooleanField(default=False)),
                ('company_phone', models.BooleanField(default=False)),
                ('company_city', models.BooleanField(default=False)),
                ('company_district', models.BooleanField(default=False)),
                ('company_title', models.BooleanField(default=False)),
                ('company_external_ip', models.BooleanField(default=False)),
                ('company_status', models.BooleanField(default=False)),
                ('company_agreement_expiry_date', models.BooleanField(default=False)),
            ],
        ),
    ]
