# Generated by Django 5.0.4 on 2024-05-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0080_updaterequest_date_joined_updaterequest_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updaterequest',
            old_name='date_joined',
            new_name='created_at',
        ),
    ]
