# Generated by Django 5.0.4 on 2024-05-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0081_rename_date_joined_updaterequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='siparis_durum',
            field=models.IntegerField(choices=[(1, 'Bekleyen'), (2, 'Hazırlandı'), (3, 'Tamamlandı'), (9, 'İptal Edildi'), (8, 'İptal Edilip Silindi')], default=0),
        ),
    ]
