# Generated by Django 5.0.4 on 2024-05-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0082_alter_siparis_siparis_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='yetki',
            name='konum_güncelle',
            field=models.BooleanField(default=False),
        ),
    ]
