# Generated by Django 5.0.4 on 2024-05-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0078_log'),
        ('kuaförApp', '0084_updaterequest_is_delete_and_more'),
    ]

    operations = [
    ]
