# Generated by Django 5.0.4 on 2024-05-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0088_error'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Error',
            new_name='ErrorReport',
        ),
    ]
