# Generated by Django 5.0.4 on 2024-05-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuaförApp', '0090_alter_siparis_siparis_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='yetki',
            name='parametre_degistir',
            field=models.BooleanField(default=False),
        ),
    ]
