"""
Django settings for kuaförProject project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-apsxh=ceb(&tbyfs!)e^2)cm)jld)^5q+slo$pisg5swfr4_kn"

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = os.getenv('DEBUG')

ALLOWED_HOSTS = ['*']



AUTH_USER_MODEL = 'kuaförApp.FirmaUser'
# Application definition
WEBSOCKET_URL = '/ws/'  # WebSocket URL'si
# settings.py



INSTALLED_APPS = [
    'channels',
    'daphne',
    'kuaförApp',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]
SCHEDULER_JOB_DEFAULTS = {
    'coalesce': False,
    'max_instances': 1
}
ASGI_APPLICATION = 'kuaförProject.asgi.application'

from django.core.asgi import get_asgi_application
# os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'kuaförProject.settings')
# application = get_asgi_application()
MIDDLEWARE = [
    # 'kuaförApp.middleware.SessionTimeoutMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
CRON_CLASSES = [
    "kuaförApp.cron.SiparisTamamlamaCronJob",
]
ROOT_URLCONF = "kuaförProject.urls"
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',  # Bu örnek, InMemoryChannelLayer'ı kullanır
    },
}
APPEND_SPLASH = False
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(BASE_DIR, 'kuaförApp', 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "kuaförApp.context_processors.check_first_time_connection",
                "kuaförApp.context_processors.custom_context_processor",
                "kuaförApp.context_processors.user_permissions",
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Statik dosyaların bulunduğu dizin
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Statik dosyaların toplanacağı dizin
# CSRF_COOKIE_SECURE = False
# CSRF_TRUSTED_ORIGINS=['http://localhost']
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
WSGI_APPLICATION = "kuaförProject.wsgi.application"
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'kuaforApp',   # PostgreSQL veritabanı adı
        'USER': 'postgres',   # PostgreSQL veritabanı kullanıcı adı
        'PASSWORD': 'serkan',  # PostgreSQL veritabanı şifresi
        'HOST': 'localhost',   # PostgreSQL servis adı (Docker Compose'da veritabanı servisinin adı)
        'PORT': '5432',   # PostgreSQL veritabanı portu (varsayılan olarak 5432)
    }
}

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = '/static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
